name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: 还原依赖
        run: dotnet restore
      
      - name: 获取版本号
        id: get_version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: 构建单文件应用
        run: |
          dotnet publish -c Release `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:PublishTrimmed=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -p:TargetFramework=net9.0 `
            -p:RuntimeIdentifier=win-x64 `
            -o ./publish
      
      - name: 打包发布文件
        run: |
          cd publish
          7z a -tzip "../PUBG-Overlay-${{ steps.get_version.outputs.VERSION }}-win-x64.zip" *
      
      - name: 创建发布
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: PUBG-Overlay-${{ steps.get_version.outputs.VERSION }}-win-x64.zip
          name: PUBG Overlay v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}